import PDFDocument from 'pdfkit';

interface ReportConfig {
  title: string;
  schoolName: string;
  dateRange: { from: string; to: string };
  generatedBy: string;
  type: string; // 'attendance' | 'fee' | 'growth' | 'crm' | 'students' | 'daily-updates'
}

interface TableConfig {
  headers: string[];
  rows: (string | number)[][];
  columnWidths: number[];
}

/**
 * Generate a PreOne-branded PDF report.
 * Returns a Buffer containing the PDF data.
 */
export async function generatePDF(config: ReportConfig, table: TableConfig): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ 
      margin: 40, 
      size: 'A4',
      info: {
        Title: config.title,
        Author: 'PreOne',
        Subject: `${config.type} report`,
      }
    });
    const buffers: Buffer[] = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // ── Purple Header Bar ──
    doc.rect(0, 0, doc.page.width, 80).fill('#7C3AED');
    
    // School name in header
    doc.font('Helvetica-Bold').fontSize(20).fillColor('#FFFFFF');
    doc.text(config.schoolName, 40, 20, { width: 300 });
    
    // PreOne branding in header right
    doc.font('Helvetica').fontSize(10).fillColor('#E0D4FC');
    doc.text('Powered by PreOne', 40, 50);
    
    // Report title in header right
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#FFFFFF');
    doc.text(config.title, 0, 30, { align: 'right', width: doc.page.width - 80 });

    // ── Meta Info ──
    const metaY = 100;
    doc.font('Helvetica').fontSize(9).fillColor('#666666');
    doc.text(`Date Range: ${config.dateRange.from} to ${config.dateRange.to}`, 40, metaY);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}`, 40, metaY + 14);
    doc.text(`Generated By: ${config.generatedBy}`, 40, metaY + 28);
    
    // Total records
    doc.text(`Total Records: ${table.rows.length}`, 40, metaY + 42);

    // ── Divider ──
    doc.moveTo(40, metaY + 58).lineTo(doc.page.width - 40, metaY + 58).strokeColor('#E5E7EB').lineWidth(1).stroke();

    // ── Table ──
    let y = metaY + 70;
    const tableWidth = table.columnWidths.reduce((a, b) => a + b, 0);
    const startX = 40;
    const rowHeight = 22;
    const headerHeight = 26;

    // Check if we need a new page
    const checkNewPage = (neededY: number) => {
      if (neededY + rowHeight > doc.page.height - 60) {
        doc.addPage();
        // Repeat header bar (thin)
        doc.rect(0, 0, doc.page.width, 40).fill('#7C3AED');
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#FFFFFF');
        doc.text(config.title, 40, 14);
        y = 55;
        // Re-draw table header
        drawTableHeader();
        return true;
      }
      return false;
    };

    const drawTableHeader = () => {
      // Header background
      doc.rect(startX, y, tableWidth, headerHeight).fill('#F3F0FF');
      
      // Header border bottom
      doc.moveTo(startX, y + headerHeight).lineTo(startX + tableWidth, y + headerHeight)
        .strokeColor('#7C3AED').lineWidth(1).stroke();
      
      // Header text
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#5B21B6');
      let x = startX + 6;
      table.headers.forEach((header, i) => {
        doc.text(header, x, y + 8, { width: table.columnWidths[i] - 12, lineBreak: false });
        x += table.columnWidths[i];
      });
      
      y += headerHeight;
    };

    drawTableHeader();

    // Data rows
    doc.font('Helvetica').fontSize(8).fillColor('#374151');
    table.rows.forEach((row, rowIdx) => {
      checkNewPage(y);
      
      // Alternating row background
      if (rowIdx % 2 === 0) {
        doc.rect(startX, y, tableWidth, rowHeight).fill('#FAFAFA');
      }
      
      // Row text
      let x = startX + 6;
      row.forEach((cell, colIdx) => {
        const cellStr = String(cell ?? '');
        doc.text(cellStr, x, y + 6, { width: table.columnWidths[colIdx] - 12, lineBreak: false });
        x += table.columnWidths[colIdx];
      });
      
      y += rowHeight;
    });

    // ── Footer ──
    const footerY = doc.page.height - 40;
    doc.font('Helvetica').fontSize(7).fillColor('#9CA3AF');
    doc.text(`PreOne — All-in-One Preschool Operating System | Confidential`, 40, footerY, { align: 'center', width: doc.page.width - 80 });

    doc.end();
  });
}
