import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'Segoe UI', 'system-ui', 'sans-serif'],
        heading: ['Poppins', 'var(--font-inter)', 'sans-serif'],
        display: ['Outfit', 'Poppins', 'sans-serif'],
        mono: ['JetBrains Mono', 'var(--font-geist-mono)', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['clamp(1.5rem, 2vw, 1.875rem)', { lineHeight: '2.25rem' }],
        '4xl': ['clamp(1.875rem, 3vw, 2.25rem)', { lineHeight: '2.5rem' }],
      },
      spacing: {
        'admin-xs': 'var(--space-xs)',
        'admin-sm': 'var(--space-sm)',
        'admin-md': 'var(--space-md)',
        'admin-lg': 'var(--space-lg)',
        'admin-xl': 'var(--space-xl)',
        'admin-2xl': 'var(--space-2xl)',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          '1': 'var(--chart-1)',
          '2': 'var(--chart-2)',
          '3': 'var(--chart-3)',
          '4': 'var(--chart-4)',
          '5': 'var(--chart-5)',
        },
        /** Portal-scoped colors */
        portal: {
          DEFAULT: 'var(--portal)',
          foreground: 'var(--portal-foreground)',
          50: 'var(--portal-50)',
          100: 'var(--portal-100)',
          200: 'var(--portal-200)',
          300: 'var(--portal-300)',
          400: 'var(--portal-400)',
          500: 'var(--portal-500)',
          600: 'var(--portal-600)',
          700: 'var(--portal-700)',
          800: 'var(--portal-800)',
          900: 'var(--portal-900)',
        },
        /** PreOne Brand colors */
        preone: {
          primary: 'var(--preone-primary)',
          'primary-dark': 'var(--preone-primary-dark)',
          'primary-light': 'var(--preone-primary-light)',
          'primary-50': 'var(--preone-primary-50)',
          'primary-100': 'var(--preone-primary-100)',
          blue: 'var(--preone-blue)',
          orange: 'var(--preone-orange)',
          pink: 'var(--preone-pink)',
          green: 'var(--preone-green)',
          coral: 'var(--preone-coral)',
        },
        /** Admin module colors */
        admin: {
          bg: 'var(--admin-bg)',
          primary: 'var(--admin-primary)',
          'primary-soft': 'var(--admin-primary-soft)',
          'primary-hover': 'var(--admin-primary-hover)',
          info: 'var(--admin-info)',
          'info-soft': 'var(--admin-info-soft)',
          warning: 'var(--admin-warning)',
          'warning-soft': 'var(--admin-warning-soft)',
          success: 'var(--admin-success)',
          'success-soft': 'var(--admin-success-soft)',
          danger: 'var(--admin-danger)',
          'danger-soft': 'var(--admin-danger-soft)',
          accent: 'var(--admin-accent)',
          'accent-soft': 'var(--admin-accent-soft)',
          text: 'var(--admin-text)',
          'text-muted': 'var(--admin-text-muted)',
          'text-subtle': 'var(--admin-text-subtle)',
          surface: 'var(--admin-surface)',
          'surface-2': 'var(--admin-surface-2)',
          border: 'var(--admin-border)',
          'border-strong': 'var(--admin-border-strong)',
        },
        /** Cosmic/Semantic colors */
        cosmic: {
          'text-primary': 'var(--text-primary)',
          'text-secondary': 'var(--text-secondary)',
          'text-tertiary': 'var(--text-tertiary)',
          'text-muted': 'var(--text-muted)',
          'bg-primary': 'var(--bg-primary)',
          'bg-secondary': 'var(--bg-secondary)',
          'bg-tertiary': 'var(--bg-tertiary)',
          'border-default': 'var(--border-default)',
          'border-light': 'var(--border-light)',
        },
      },
      screens: {
        'xs': '475px',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 4px)',
        sm: 'calc(var(--radius) - 8px)',
        xl: '20px',
        '2xl': '24px',
        '3xl': '28px',
        '4xl': '32px',
        card: '24px',
        container: '20px',
        element: '16px',
        badge: '12px',
      },
      boxShadow: {
        'card': '0px 8px 24px rgba(15,23,42,0.06)',
        'card-hover': '0px 20px 40px rgba(15,23,42,0.08)',
        'floating': '0px 30px 60px rgba(15,23,42,0.10)',
        'portal': '0px 8px 24px rgba(15,23,42,0.06)',
        'glow': 'var(--shadow-glow)',
        'glow-dark': '0 0 20px rgba(108, 92, 231, 0.25)',
        'hero': '0 10px 25px rgba(99, 102, 241, 0.25)',
        'hero-dark': '0 10px 25px rgba(108, 92, 231, 0.35)',
        'admin-xs': 'var(--shadow-xs)',
        'admin-sm': 'var(--shadow-sm)',
        'admin-md': 'var(--shadow-md)',
        'admin-lg': 'var(--shadow-lg)',
        'admin-xl': 'var(--shadow-xl)',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '240ms',
        'smooth': '350ms',
        'spring': '500ms',
        'theme': '300ms',
      },
      keyframes: {
        twinkle: {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'aurora-shift': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 8px rgba(99, 102, 241, 0.2)' },
          '50%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.4)' },
        },
      },
      animation: {
        twinkle: 'twinkle 3s ease-in-out infinite',
        float: 'float 4s ease-in-out infinite',
        'aurora-shift': 'aurora-shift 15s ease infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
export default config;
